apps/menu/urls.py
from django.urls import re_path
from apps.menu.views import (
    TicketGeneralCreateView,
    TicketDetalleCreateView,
    TicketDetalleDeleteView,
    TicketGeneralListView,
    AjaxView,
    TicketGeneralDeleteView, 
    TicketGeneralDetailView, 
    ResumenGeneralView, 
    InicioFinConsultaView, 
    ResumenInicioFinView
)

urlpatterns = [
    re_path(r'^crear/ticket/(?P<pk>)$', TicketGeneralCreateView.as_view(), name="crear_ticket"),
    re_path(r'^borrar/ticket/(?P<pk>)$', TicketGeneralDeleteView.as_view(), name="borrar_ticket"),
    re_path(r'^detalle/ticket/(?P<pk>)$', TicketGeneralDetailView.as_view(), name="detalle_ticket"),
    re_path(r'^crear/detalle/(?P<pk>)$', TicketDetalleCreateView.as_view(), name="crear_detalle"),
    re_path(r'^borrar/detalle/(?P<pk>)$', TicketDetalleDeleteView.as_view(), name="borrar_detalle"),
    re_path(r'^listar/tickets/(?P<dia>[\w])$', TicketGeneralListView.as_view(), name="listar_ticket"),
    re_path(r'^resumen/tickets/(?P<date>\d{4}-\d{2}-\d{2})/$', ResumenGeneralView.as_view(), name="resumen_ticket"),
    re_path(r'^resumen/inicio/(?P<inicio>\d{4}-\d{2}-\d{2})/fin/(?P<fin>\d{4}-\d{2}-\d{2})$', ResumenInicioFinView.as_view(), name="resumen_inicio_fin"),
    re_path(r'^resumen/consulta/$', InicioFinConsultaView.as_view(), name="inicio_fin_consulta"),
    re_path(r'^ajax/$', AjaxView.as_view()),
]

dogaut/urls.py
from django.urls import re_path, include
from django.contrib import admin

urlpatterns = [
    re_path(r'^caronte/', admin.site.urls),
    re_path(r'^', include('apps.login.urls')),
    re_path(r'^dashboard/', include('apps.dashboard.urls')),
    re_path(r'^menu/', include('apps.menu.urls')),
    re_path(r'^encuesta/', include('apps.encuesta.urls')),
]

apps/menu/models.py
from django.db import models
from apps.catalogo.models import TimeStamp, ClasificadorMenu, Ingrediente
from apps.empleados.models import Empleado


class Servicio(TimeStamp):
    nombre = models.CharField(max_length=50, help_text="Nombre del platillo o bebida")
    precio = models.IntegerField(help_text='Precio de servicio')
    descripcion = models.TextField(help_text="Descripcion del platillo o bebida")
    clasificacion = models.ForeignKey(ClasificadorMenu, on_delete=models.CASCADE)

    def precioServicio(self):
        return self.precio_set.get(estatus__clave='ACT').precio

    def __str__(self):
        return "%s" % self.nombre

    class Meta:
        verbose_name_plural = 'Servicios'


class HistorialPrecio(TimeStamp):
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)
    precio = models.IntegerField()


class Preparacion(TimeStamp):
    servicio = models.ForeignKey(Servicio, help_text="Servicios que tenga como clasificacion alimentos y licor", on_delete=models.CASCADE)
    preparacion = models.TextField(help_text="Detalles del modo de preparacion")
    observaciones = models.TextField(help_text="Alguna observacion pertinente", null=True, blank=True)

    def __str__(self):
        return "%s %s" % (self.servicio, self.observaciones)

    class Meta:
        verbose_name_plural = "Preparacion recetas"


class TicketGeneral(TimeStamp):
    TIPO_PAGO = (
        (1, 'Efectivo'),
        (2, 'Tarjeta credito'),
        (3, 'Tarjeta debito'),
    )
    fecha = models.DateField(help_text='Fecha del consumo')
    mesa = models.IntegerField(help_text='Mesa que realizo el consumo')
    mesero = models.ForeignKey(Empleado, help_text='Mesero que atendio', on_delete=models.CASCADE)
    pago = models.IntegerField(choices=TIPO_PAGO, help_text="Tipo de pago")
    factura = models.BooleanField(help_text='Indica si se facturo el consumo')
    detalle = models.ManyToManyField('TicketDetalle', null=True, blank=True)

    def totalTicket(self):
        total = 0
        for detalle in self.ticketdetalle_set.filter():
            total += (detalle.precio * detalle.cantidad)
        return total

    def __str__(self):
        return "Mesa: %s Mesero: %s" % (self.mesa, self.mesero.alias)

    class Meta:
        verbose_name_plural = "Ticket general"


class TicketDetalle(TimeStamp):
    ticket_general = models.ForeignKey(TicketGeneral, on_delete=models.CASCADE)
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)
    precio = models.IntegerField()
    cantidad = models.IntegerField()
    observacion = models.CharField(max_length=50, null=True, blank=True)

    def subTotal(self):
        return self.precio * self.cantidad

    def __str__(self):
        return "%s" % self.servicio

    class Meta:
        verbose_name_plural = "Ticket detalle"

apps/menu/forms.py
from django import forms
from datetime import datetime
from apps.menu.models import TicketGeneral


class TicketGeneralForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
       super(TicketGeneralForm, self).__init__(*args, **kwargs)
       hoy = datetime.now()
       hoyFormateado = hoy.strftime("%Y-%m-%d")
       self.fields['fecha'].initial = hoyFormateado
       self.fields['pago'].initial = 1

    class Meta:
        model = TicketGeneral
        fields = ['fecha', 'mesero', 'pago', 'factura']
        widgets = {
                'fecha': forms.DateTimeInput(attrs={'class': 'form-control datepicker'}),
                'mesero': forms.Select(attrs={'class': 'form-control'}),
                'pago': forms.Select(attrs={'class': 'form-control'}),
                'factura': forms.CheckboxInput(attrs={'class': 'form-control'}),
        }


class InicioFinConsultaForm(forms.Form):
    inicio = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control datepicker'}))
    fin = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control datepicker'}))

apps/menu/views.py
from django.views.generic import CreateView, DeleteView, ListView, TemplateView, DetailView, FormView
from django import forms
from django.db import transaction
from braces.views import GroupRequiredMixin
from django.db.models import Sum
from django.core import serializers
from django.http import HttpResponse
from django.contrib import messages
from datetime import datetime, timedelta
from django.urls import reverse
from apps.menu.models import TicketGeneral, TicketDetalle, Servicio
from apps.menu.forms import TicketGeneralForm, InicioFinConsultaForm


class TicketGeneralCreateView(GroupRequiredMixin, FormView):
    form_class = TicketGeneralForm
    template_name = 'plantillas/crear.html'
    group_required = [u'barman']
    raise_exception = True
    ticketID = 0

    def get_context_data(self, **kwargs):
        context = super(TicketGeneralCreateView, self).get_context_data(**kwargs)
        data = {
            'title': 'Crear Ticket Mesa ',
            'mesa': self.kwargs['pk'],
            'medidaInput' : 4,
        }
        context.update(data)
        return context

    @transaction.atomic()
    def form_valid(self, form):
        form.instance.usuario_crea = self.request.user
        form.instance.mesa = self.kwargs['pk']
        f = form.save()
        self.ticketID = f.id
        messages.success(self.request, "Creado %s con exito" % (f))
        return super(TicketGeneralCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('crear_detalle', kwargs={'pk': self.ticketID })


class TicketGeneralDeleteView(GroupRequiredMixin, DeleteView):
    model = TicketGeneral
    template_name = 'plantillas/borrar.html'
    success_message = "La comanda se elimino con exito"
    group_required = [u'barman']
    raise_exception = True

    def delete(self, request, *args, **kwargs):
        messages.warning(self.request, self.success_message)
        return super(TicketGeneralDeleteView, self).delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('listar_ticket', kwargs={'dia': 'hoy'})


class TicketGeneralListView(GroupRequiredMixin, ListView):
    model = TicketGeneral
    template_name = 'plantillas/lista.html'
    ordering = 'id'
    group_required = [u'barman']
    raise_exception = True

    def get_context_data(self, **kwargs):
        hoy = datetime.now()
        context = super(TicketGeneralListView, self).get_context_data(**kwargs)
        if self.kwargs.get('dia') == 'hoy':
            dia = hoy.strftime("%Y-%m-%d")
        if self.kwargs.get('dia') == 'ayer':
            ayer = hoy - timedelta(days=1)
            dia = ayer.strftime("%Y-%m-%d")
        data = {
            'title': 'Resumen %s' % (dia),
            'empty_message': 'Parece que aun no se registra ninguna venta',
            'borrar_url': 'borrar_ticket',
            'detalle_url': 'detalle_ticket',
            'editar_url': 'crear_detalle',
            'resumen_url': 'resumen_ticket',
            'dia': dia,
        }
        context.update(data)
        return context

    def get_queryset(self):
        hoy = datetime.now()
        ayer = hoy - timedelta(days=1)
        if self.kwargs.get('dia')== 'hoy':
            queryset = self.model.objects.filter(fecha__year=hoy.year, fecha__month=hoy.month, fecha__day=hoy.day)
        if self.kwargs.get('dia')== 'ayer':
            queryset = self.model.objects.filter(fecha__year=ayer.year, fecha__month=ayer.month, fecha__day=ayer.day)
        return queryset


class TicketGeneralDetailView(DetailView):
    model = TicketGeneral
    template_name = 'menu/detalle_ticket.html'


class ResumenGeneralView(TemplateView):
    template_name = 'menu/resumen.html'

    def get_context_data(self, **kwargs):
        context = super(ResumenGeneralView,self).get_context_data(**kwargs)
        dia = self.kwargs['date']
        serviciosTotales = TicketDetalle.objects.values('servicio__nombre').annotate(cantidad=Sum('cantidad')).\
                filter(ticket_general__fecha=dia).order_by('servicio__id')
        # total en dinero
        detalles = TicketDetalle.objects.filter(ticket_general__fecha=dia)
        totalMonetario = 0
        for detalle in detalles:
            totalMonetario += detalle.precio * detalle.cantidad
        data = {
            'title' : 'Resumen %s' %(dia),
            'totalMonetario' : totalMonetario,
            'serviciosTotales': serviciosTotales,
        }
        context.update(data)
        return context


class TicketDetalleCreateView(GroupRequiredMixin, CreateView):
    model = TicketDetalle
    fields = ['servicio', 'precio', 'cantidad', 'observacion']
    template_name = 'menu/crear_detalle.html'
    group_required = [u'barman']
    raise_exception = True

    def get_context_data(self, **kwargs):
        context = super(TicketDetalleCreateView, self).get_context_data(**kwargs)
        ticketGeneral = TicketGeneral.objects.get(id=self.kwargs['pk'])
        detalles = TicketDetalle.objects.filter(ticket_general=ticketGeneral)
        total = 0
        for d in detalles:
            total += d.precio * d.cantidad
        data = {
            'titleDetalle': 'Comanda',
            'ticketGeneral': ticketGeneral,
            'title' : 'Agregar alimento bebida postre',
            'medidaInput' : 6,
            'total' : total,
            'borrar_url' : 'borrar_detalle',
            'ajax_url' : 'ajax',
        }
        context.update(data)
        return context

    @transaction.atomic()
    def get_form(self, form_class=None):
        form = super(TicketDetalleCreateView, self).get_form()
        form.fields['servicio'].widget = forms.Select(attrs={'class':'form-control'})
        form.fields['servicio'].queryset = Servicio.objects.all()
        form.fields['precio'].widget = forms.TextInput(attrs={'class':'form-control'})
        form.fields['observacion'].widget = forms.Textarea(attrs={'class':'form-control', 'rows' : 3})
        form.fields['cantidad'].widget = forms.TextInput(attrs={'class':'form-control'})
        form.initial = {'cantidad' : 1}
        return form

    def form_valid(self, form):
        form.instance.usuario_crea = self.request.user
        form.instance.ticket_general = TicketGeneral.objects.get(id=self.kwargs['pk'])
        f = form.save()
        messages.success(self.request, "Creado %s con exito" % (f))
        return super(TicketDetalleCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('crear_detalle', kwargs={'pk': self.kwargs['pk']})


class TicketDetalleDeleteView(GroupRequiredMixin, DeleteView):
    model = TicketDetalle
    template_name = 'plantillas/borrar.html'
    success_message = "El servicio se elimino con exito"
    group_required = [u'barman']
    raise_exception = True

    def delete(self, request, *args, **kwargs):
        messages.warning(self.request, self.success_message)
        return super(TicketDetalleDeleteView, self).delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('crear_detalle', kwargs={'pk': self.object.ticket_general.id})


class AjaxView(TemplateView):

    def get(self,request, *args, **kwargs):
        envioAjax = request.GET['envio']
        servicios = Servicio.objects.filter(nombre__contains=envioAjax.upper())
        data = serializers.serialize('json', servicios, fields=('id', 'nombre', 'precio'))
        return HttpResponse(data)


class InicioFinConsultaView(FormView):
    form_class = InicioFinConsultaForm
    template_name = 'plantillas/crear.html'

    def get_context_data(self, **kwargs):
        contex = super(InicioFinConsultaView,self).get_context_data(**kwargs)
        data = {
            'title' : 'Cosultar ventas',
        }
        contex.update(data)
        return contex

    def form_valid(self, form):
        messages.success(self.request, "Consulta exitosa")
        return super(InicioFinConsultaView,self).form_valid(form)

    def get_success_url(self):
        return reverse('resumen_inicio_fin', kwargs={'inicio': self.request.POST['inicio'], 'fin': self.request.POST['fin']})


class ResumenInicioFinView(TemplateView):
    template_name = 'menu/resumen.html'

    def get_context_data(self, **kwargs):
        context = super(ResumenInicioFinView,self).get_context_data(**kwargs)
        inicio = self.kwargs['inicio']
        fin = self.kwargs['fin']
        serviciosTotales = TicketDetalle.objects.values('servicio__nombre').annotate(cantidad=Sum('cantidad')).\
                filter(ticket_general__fecha__range=[inicio,fin]).order_by('servicio__id')
        # total en dinero
        detalles = TicketDetalle.objects.filter(ticket_general__fecha__range=[inicio,fin])
        totalMonetario = 0
        for detalle in detalles:
            totalMonetario += detalle.precio * detalle.cantidad
        data = {
            'title' : 'Resumen del %s al %s' %(inicio, fin),
            'totalMonetario' : totalMonetario,
            'serviciosTotales': serviciosTotales,
        }
        context.update(data)
        return context

templates/menu/crear_detalle.html
{% extends 'plantillas/base.html' %}

{% block contenido %}
    {% include 'plantillas/navbar.html' %}
    {% include 'plantillas/mensaje.html' %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>{{ titleDetalle }}</h1>
                <div class="panel panel-primary">
                      <div class="panel-heading">
                          <h4 class="app-centrar">Mesa {{ ticketGeneral.mesa }}</h4>
                      </div>
                      <table class="table table-striped">
                          <tr>
                              <th>Fecha</th>
                              <th>Mesero</th>
                              <th>Pago</th>
                              <th>Factura</th>
                              <th>Total</th>
                          </tr>
                          <tr>
                              <td>{{ ticketGeneral.fecha }}</td>
                              <td>{{ ticketGeneral.mesero }}</td>
                              <td>{{ ticketGeneral.get_pago_display }}</td>
                              <td>{% if ticketGeneral.factura %}Si{% else %}No{% endif %}</td>
                              <td>$ {{ total }}</td>
                          </tr>
                      </table>
                      {% if ticketGeneral.ticketdetalle_set.all %}
                          <div  class="panel panel-info">
                              <div class="panel-heading app-centrar">
                                <h4>Servicios</h4>
                              </div>
                              <div class="panel-body">
                                <table class="table table-striped">
                                  <thead>
                                      <tr>
                                          <th>Nombre</th>
                                          <th>Cantidad</th>
                                          <th>Precio u.</th>
                                          <th></th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                    {% for detalle in  ticketGeneral.ticketdetalle_set.all %}
                                        <tr>
                                            <td>{{ detalle.servicio }} </td>
                                            <td>{{ detalle.cantidad }} </td>
                                            <td>$ {{ detalle.precio }} </td>
                                            <td> <a href="{% url borrar_url detalle.id %}"><span class="glyphicon glyphicon-remove"></span></a></td>
                                        </tr>
                                    {% endfor %}
                                  </tbody>
                                </table>
                              </div>
                          </div>
                          <div class="container-fluid">
                              <div class="row">
                                  <div class="col-md-offset-8 col-md-3">
                                      <div class="panel panel-danger">
                                          <div class="panel-heading panel-total app-centrar">Total: ${{ total }}</div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <h1 class="title_crear">{{ title }} {{ mesa }}</h1>
                    <form class="form-horizontal" autocomplete="off" method="post" role="form">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-md-8">
                                <input placeholder="Buscar" id="busca" class="form-control" maxlength="20">
                            </div>
                        </div>
                        {% include 'plantillas/form.html' %}
                        <div class="col-md-6 col-sm-offset-6 ">
                            <input type="submit" value="Crear" id="crear" class="btn btn-success">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block complementoJS %}
    <script type="text/javascript">
        $(document).ready(function(){
            var busca = $('#busca');
            busca.autocomplete({
                source : function (request, response) {
                    var servicioID=0;
                    var servicioPrecio=0;
                    $.ajax({
                        url : '/menu/ajax/',
                        dataType:'json',
                        data:{envio:request.term},
                        success: function (data) {
                            var sugerencias = [];
                            $.each(data, function(index,objeto){
                                sugerencias.push(objeto.fields.nombre);
                            });
                            response(sugerencias);

                            busca.blur(function(event){
                                valor = busca.val();
                                for(i=0; i<data.length;i++) {
                                    if(data[i].fields.nombre==valor){
                                        servicioID = data[i].pk;
                                        servicioPrecio = data[i].fields.precio;
                                    }
                                }
                                $('#id_servicio').val(servicioID);
                                $('#id_precio').val(servicioPrecio);
                            });
                        }
                    });
                },
                minLength:3,
            });
        });
    </script>
{% endblock %}

templates/menu/detalle_ticket.html
{% extends 'plantillas/base.html' %}

{% block contenido %}
    {% include 'plantillas/navbar.html' %}
    {% include 'plantillas/mensaje.html' %}

    <div class="container container-margin">
        <div class="row">
            <div class="col-md-5 col-md-offset-1">
                <div class="panel panel-info">
                    <div class="panel-heading app-centrar panel-total">
                        Comanda
                    </div>
                    <table class="table">
                        <tr>
                            <th>Mesa:</th>
                            <td>{{ object.mesa}}</td>
                        </tr>
                        <tr>
                            <th>Fecha de consumo:</th>
                            <td>{{ object.fecha }}</td>
                        </tr>
                        <tr>
                            <th>Guardo</th>
                            <td>{{ object.usuario_crea }}</td>
                        </tr>
                        <tr>
                            <th>fecha de creacion</th>
                            <td>{{ object.creado }}</td>
                        </tr>
                        <tr>
                            <th>Mesero</th>
                            <td>{{ object.mesero }}</td>
                        </tr>
                        <tr>
                            <th>Tipo de pago</th>
                            <td>{{ object.get_pago_display }}</td>
                        </tr>
                        <tr>
                            <th>Facturo</th>
                            <td>{% if object.factura %}Si{% else %}No{% endif %}</td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="col-md-5 ">
                <div class="panel panel-success">
                    <div class="panel-heading app-centrar panel-total">
                        Consumo
                    </div>
                    <table class="table">
                        {% for detalle in object.ticketdetalle_set.all %}
                            <tr>
                                <th>{{ detalle.cantidad }}</th>
                                <th>{{ detalle }}</th>
                                <td>{% if detalle.observacion %}{{ detalle.observacion }}{% endif %}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/menu/resumen.html
{% extends 'plantillas/base.html' %}
{% block contenido %}
    {% include 'plantillas/navbar.html' %}
    {% include 'plantillas/mensaje.html' %}

    <div class="container container-margin">
        <div class="row">
            <div class="col-md-5 col-md-offset-3">
                <h2 class="app-centrar">{{ title }}</h2>
                <div class="panel panel-primary">
                    <div class="panel-heading app-centrar">Total</div>
                    <div class="panel-body app-centrar">
                        <span class="label label-warning label-total">{{ totalMonetario }}</span>
                    </div>
                    <ul class="list-group">
                        {% for i in serviciosTotales %}
                            <li class="list-group-item">{{ i.servicio__nombre }} <span class="badge">{{ i.cantidad }}</span></li>
                        {% endfor %}
                     </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}